In [141]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder

In [ ]:
#data_snp_phenotype = pd.read_csv('../data/data_snp_phenotype_012.zip', sep=',')

Полный датафрейм не загружается, "ОЗУ полностью исчерпан" ☹. Взяла только первые 1000 столбцов

In [ ]:
data_snp_phenotype_filtered = pd.read_csv('../data/data_snp_phenotype_filtered_012.csv.zip', sep=',')

In [7]:
data_snp_phenotype_filtered

,Accession,NC_024459.2,NC_024459.2.1,NC_024459.2.2,NC_024459.2.3,NC_024459.2.4,NC_024459.2.5,NC_024459.2.6,NC_024459.2.7,NC_024459.2.8,...,NC_024459.2.990,NC_024459.2.991,NC_024459.2.992,NC_024459.2.993,NC_024459.2.994,NC_024459.2.995,NC_024459.2.996,NC_024459.2.997,NC_024459.2.998,Heterotic group
0,CRR504157,1|0,1|1,1|0,0|1,1|1,1|0,1|0,1|0,1|0,...,1|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,NSS
1,CRR504163,1|0,1|1,1|0,1|1,1|1,1|0,1|0,1|0,1|0,...,1|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,SPT
2,CRR504172,1|0,1|0,1|0,1|1,1|1,0|1,0|1,0|1,0|1,...,1|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,NSS
3,CRR504174,0|1,0|1,0|1,0|0,0|0,0|0,0|0,0|0,0|0,...,1|1,0|0,0|0,0|0,0|0,0|0,1|1,1|1,1|1,PB
4,CRR504181,0|0,1|1,0|0,1|1,1|1,1|0,1|0,1|0,1|0,...,1|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,PA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,CRR505744,0|1,1|1,0|1,1|1,1|1,0|1,0|1,0|1,0|1,...,1|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,PA
601,CRR505746,0|1,1|1,0|1,1|1,1|1,0|1,0|1,0|1,0|1,...,1|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,PA
602,CRR505747,1|0,1|1,1|0,1|1,1|1,1|0,1|0,1|0,1|0,...,1|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,PA
603,CRR505752,1|0,1|0,1|0,0|0,0|0,0|0,0|0,0|0,0|0,...,1|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,PA
604,CRR505754,0|1,0|1,0|1,0|1,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,NSS

In [8]:
df_wo_accession = data_snp_phenotype_filtered.drop(columns=['Accession'])

all_values = df_wo_accession.values.flatten()

unique_values = pd.unique(all_values)

In [9]:
unique_values

array(['1|0', '1|1', '0|1', '0|0', 'NSS', 'SPT', '2|0', '2|1', 'PB', 'PA',
       'SS', '0|2', '2|2', '1|2', 'Admix', 'Iodent'], dtype=object)

In [36]:
# Divide the data into X as a data for learning models aka features and y as a data the model should predict aka target
X = data_snp_phenotype_filtered.drop(columns=["Accession", "Heterotic group"]) # Генотипы
y = data_snp_phenotype_filtered["Heterotic group"]  # гетерозисная группа

In [37]:
X

,NC_024459.2,NC_024459.2.1,NC_024459.2.2,NC_024459.2.3,NC_024459.2.4,NC_024459.2.5,NC_024459.2.6,NC_024459.2.7,NC_024459.2.8,NC_024459.2.9,...,NC_024459.2.989,NC_024459.2.990,NC_024459.2.991,NC_024459.2.992,NC_024459.2.993,NC_024459.2.994,NC_024459.2.995,NC_024459.2.996,NC_024459.2.997,NC_024459.2.998
0,1|0,1|1,1|0,0|1,1|1,1|0,1|0,1|0,1|0,1|0,...,1|1,1|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
1,1|0,1|1,1|0,1|1,1|1,1|0,1|0,1|0,1|0,1|0,...,1|1,1|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
2,1|0,1|0,1|0,1|1,1|1,0|1,0|1,0|1,0|1,0|1,...,1|1,1|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
3,0|1,0|1,0|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,1|1,1|1,0|0,0|0,0|0,0|0,0|0,1|1,1|1,1|1
4,0|0,1|1,0|0,1|1,1|1,1|0,1|0,1|0,1|0,1|0,...,1|1,1|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,0|1,1|1,0|1,1|1,1|1,0|1,0|1,0|1,0|1,0|1,...,1|1,1|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
601,0|1,1|1,0|1,1|1,1|1,0|1,0|1,0|1,0|1,0|1,...,1|1,1|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
602,1|0,1|1,1|0,1|1,1|1,1|0,1|0,1|0,1|0,1|0,...,1|1,1|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
603,1|0,1|0,1|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|1,1|1,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
604,0|1,0|1,0|1,0|1,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0

In [12]:
y

0      NSS
1      SPT
2      NSS
3       PB
4       PA
      ...
600     PA
601     PA
602     PA
603     PA
604    NSS
Name: Heterotic group, Length: 605, dtype: object

In [13]:
def convert_genotype(genotype):
    """Конвертирует строку '1|0', '1|1', '0|1', '0|0', '2|0', '2|1', '0|2', '2|2', '1|2'  в категориальные значения"""
    if genotype == "1|1":
        return 0
    elif genotype == "0|0":
        return 1
    elif genotype == "2|2":
        return 2
    elif genotype == "1|0" or genotype == "0|1":
        return 3
    elif genotype == "2|0" or genotype == "0|2":
        return 4
    else:
        return 5    # "1|2" or "2|1"

In [38]:
X = X.applymap(convert_genotype)

<ipython-input-38-f7d5e4721e2e>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  X = X.applymap(convert_genotype)

In [39]:
X

,NC_024459.2,NC_024459.2.1,NC_024459.2.2,NC_024459.2.3,NC_024459.2.4,NC_024459.2.5,NC_024459.2.6,NC_024459.2.7,NC_024459.2.8,NC_024459.2.9,...,NC_024459.2.989,NC_024459.2.990,NC_024459.2.991,NC_024459.2.992,NC_024459.2.993,NC_024459.2.994,NC_024459.2.995,NC_024459.2.996,NC_024459.2.997,NC_024459.2.998
0,3,0,3,3,0,3,3,3,3,3,...,0,0,1,1,1,1,1,1,1,1
1,3,0,3,0,0,3,3,3,3,3,...,0,0,1,1,1,1,1,1,1,1
2,3,3,3,0,0,3,3,3,3,3,...,0,3,1,1,1,1,1,1,1,1
3,3,3,3,1,1,1,1,1,1,1,...,0,0,1,1,1,1,1,0,0,0
4,1,0,1,0,0,3,3,3,3,3,...,0,0,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,3,0,3,0,0,3,3,3,3,3,...,0,0,1,1,1,1,1,1,1,1
601,3,0,3,0,0,3,3,3,3,3,...,0,0,1,1,1,1,1,1,1,1
602,3,0,3,0,0,3,3,3,3,3,...,0,0,1,1,1,1,1,1,1,1
603,3,3,3,1,1,1,1,1,1,1,...,3,0,1,1,1,1,1,1,1,1
604,3,3,3,3,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [16]:


all_values_X = X.values.flatten()

unique_values = pd.unique(all_values_X)

In [17]:
unique_values

array([3, 0, 1, 4, 5, 2])

In [28]:
X.dtypes

NC_024459.2        int64
NC_024459.2.1      int64
NC_024459.2.2      int64
NC_024459.2.3      int64
NC_024459.2.4      int64
                   ...
NC_024459.2.994    int64
NC_024459.2.995    int64
NC_024459.2.996    int64
NC_024459.2.997    int64
NC_024459.2.998    int64
Length: 999, dtype: object

In [31]:
#X_one_hot = X_one_hot.astype(str)

In [40]:
X_one_hot = X.apply(pd.Categorical)

In [41]:
X_one_hot.dtypes

NC_024459.2        category
NC_024459.2.1      category
NC_024459.2.2      category
NC_024459.2.3      category
NC_024459.2.4      category
                     ...
NC_024459.2.994    category
NC_024459.2.995    category
NC_024459.2.996    category
NC_024459.2.997    category
NC_024459.2.998    category
Length: 999, dtype: object

In [42]:
X_one_hot = pd.get_dummies(X_one_hot)

In [44]:
X_one_hot = X_one_hot.astype(int)

In [45]:
X_one_hot

,NC_024459.2_0,NC_024459.2_1,NC_024459.2_3,NC_024459.2.1_0,NC_024459.2.1_1,NC_024459.2.1_3,NC_024459.2.2_0,NC_024459.2.2_1,NC_024459.2.2_3,NC_024459.2.3_0,...,NC_024459.2.995_3,NC_024459.2.996_0,NC_024459.2.996_1,NC_024459.2.996_3,NC_024459.2.997_0,NC_024459.2.997_1,NC_024459.2.997_3,NC_024459.2.998_0,NC_024459.2.998_1,NC_024459.2.998_3
0,0,0,1,1,0,0,0,0,1,0,...,0,0,1,0,0,1,0,0,1,0
1,0,0,1,1,0,0,0,0,1,1,...,0,0,1,0,0,1,0,0,1,0
2,0,0,1,0,0,1,0,0,1,1,...,0,0,1,0,0,1,0,0,1,0
3,0,0,1,0,0,1,0,0,1,0,...,0,1,0,0,1,0,0,1,0,0
4,0,1,0,1,0,0,0,1,0,1,...,0,0,1,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,0,0,1,1,0,0,0,0,1,1,...,0,0,1,0,0,1,0,0,1,0
601,0,0,1,1,0,0,0,0,1,1,...,0,0,1,0,0,1,0,0,1,0
602,0,0,1,1,0,0,0,0,1,1,...,0,0,1,0,0,1,0,0,1,0
603,0,0,1,0,0,1,0,0,1,0,...,0,0,1,0,0,1,0,0,1,0
604,0,0,1,0,0,1,0,0,1,0,...,0,0,1,0,0,1,0,0,1,0

In [46]:
unique_values_per_column = X.nunique()

print(unique_values_per_column[unique_values_per_column < 6])

NC_024459.2        3
NC_024459.2.1      3
NC_024459.2.2      3
NC_024459.2.3      3
NC_024459.2.4      3
                  ..
NC_024459.2.994    3
NC_024459.2.995    3
NC_024459.2.996    3
NC_024459.2.997    3
NC_024459.2.998    3
Length: 993, dtype: int64

In [47]:
y = y.astype("category").cat.codes

In [48]:
y

0      2
1      5
2      2
3      4
4      3
      ..
600    3
601    3
602    3
603    3
604    2
Length: 605, dtype: int8

In [139]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [143]:
random_forest_model = RandomForestClassifier(random_state=123, n_estimators=15, max_depth=3, min_samples_split=7, min_samples_leaf=6)


random_forest_model.fit(X_train, y_train)

train_accuracy = random_forest_model.score(X_train, y_train)
test_accuracy = random_forest_model.score(X_test, y_test)

print("Обучающая выборка:", train_accuracy)
print("Тестовая выборка:", test_accuracy)

Обучающая выборка: 0.640495867768595
Тестовая выборка: 0.6033057851239669

Изменение параметров приводило либо к переобучению, либо к недообучению